/**
 * Function calculates the total users and asign a random id 
 * @param {[]} users - Array with the elements in the db.
 * @param {number} randomNum - Random number generated by the function randomNum.
 */
export const generateId = (users, randomNum) => { 
    const id = randomNum;
    return 'USR_%-' + id + users.length;
 }